version: 2

project_name: slack-cli

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - main: ./cmd/slack-cli
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/piekstra/slack-cli/internal/version.Version={{.Version}}
      - -X github.com/piekstra/slack-cli/internal/version.Commit={{.Commit}}
      - -X github.com/piekstra/slack-cli/internal/version.Date={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "Merge pull request"
  groups:
    - title: Features
      regexp: '^feat:'
      order: 0
    - title: Bug Fixes
      regexp: '^fix:'
      order: 1
    - title: Other
      order: 999

brews:
  - name: slack-cli
    repository:
      owner: piekstra
      name: homebrew-tap
    directory: Formula
    homepage: "https://github.com/piekstra/slack-cli"
    description: "Command-line interface for Slack"
    license: "MIT"
    install: |
      bin.install "slack-cli"
    caveats: |
      To configure slack-cli, run:
        slack-cli config set-token <your-slack-api-token>

      Or set the SLACK_API_TOKEN environment variable.
    test: |
      assert_match "slack-cli", shell_output("#{bin}/slack-cli --help")
